site_name: Incendia Documentation
site_url: https://www.incendia.tech/
repo_url: https://github.com/zero-savvy/burn-to-vote
theme:
  name: material
  logo: images/incendia-logo.png
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - content.code.copy
extra:
  homepage: true

extra_css:
  - stylesheets/extra.css
nav:
  - Home: index.md
  - Getting Started:
      - Installation: installation.md
      - Usage: usage.md
  - Developer Guide:
      - Architecture: dev/architecture.md
      - Contributing: dev/contributing.md
      - Roadmap: dev/roadmap.md
  # - API Reference: api.md
