site_name: Incendia Documentation
site_url: https://www.incendia.tech/
repo_url: https://github.com/incendia-tech
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.expand
    - content.code.copy
nav:
  - Home: index.md
  - Getting Started:
      - Installation: installation.md
      - Usage: usage.md
  - Developer Guide:
      - Contributing: dev/contributing.md
      - Architecture: dev/architecture.md
      - Roadmap: dev/roadmap.md
  - API Reference: api.md
